# Generated by Django 6.0.5 on 2026-06-19 05:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0002_remove_order_user_order_full_name_order_phone_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='flow',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='apps.flow'),
        ),
    ]
