# Generated by Django 6.0.5 on 2026-06-19 05:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0004_order_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('admin', 'Admin'), ('deliver', 'Deliver')], default=''),
        ),
    ]
