# Generated by Django 6.0.5 on 2026-06-19 06:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0006_order_city'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('packing', 'Packing'), ('delivering', 'Delivering'), ('delivered', 'Delivered'), ('postponed', 'Postponed'), ('returned', 'Returned'), ('cancelled', 'Cancelled'), ('hold', 'Hold'), ('archive', 'Archive'), ('ready', 'Ready')], default='packing'),
        ),
    ]
